//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalCareCenterEntities : DbContext
    {
        public MedicalCareCenterEntities()
            : base("name=MedicalCareCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblPatient> tblPatients { get; set; }
        public virtual DbSet<tblSickLeave> tblSickLeaves { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<vwDoctor> vwDoctors { get; set; }
        public virtual DbSet<vwPatient> vwPatients { get; set; }
        public virtual DbSet<vwSickLeave> vwSickLeaves { get; set; }
        public virtual DbSet<vwUser> vwUsers { get; set; }
    }
}
