//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSickLeave
    {
        public int RequestId { get; set; }
        public System.DateTime RequestSendDate { get; set; }
        public string SLReason { get; set; }
        public string Company { get; set; }
        public string CaseOfEmergency { get; set; }
        public int PatientId { get; set; }
    
        public virtual tblPatient tblPatient { get; set; }
    }
}
