//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSickLeave
    {
        public int PatientId { get; set; }
        public int UserId { get; set; }
        public string HealthInsuranceCardNo { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string CaseOfEmergency { get; set; }
        public string Company { get; set; }
        public System.DateTime RequestSendDate { get; set; }
        public string SLReason { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}
